#!/usr/bin/make

########################################################################

# *** Fill out this information *** 

#  Project Name
PROJECT = remote_controlled_car
#  List of the objects files to be compiled/assembled
OBJECTS = auto.o 
#OBJECTS = control.o i2c_accelerometer.o 

# Selected architecture/board
ARCH = lpc17xx/mbed
# Programming language for this project (C for C, CPP for C++)
LANGUAGE = CPP

# Compiling options
DEBUG = 
OPTIMIZATION = 2
CFLAGS = -Wall

########################################################################

# Path to the library
LIB_BASE := ../../src

# Include libmanyuc's Makefile to take care of the rest
include $(LIB_BASE)/Makefile

