#!/usr/bin/make

#  List of the objects files to be compiled/assembled
MODULE_PORT_OBJECTS = spi.o
PORT_OBJECTS += $(addprefix $(MODULE_ARCH_DIR)/, $(MODULE_PORT_OBJECTS))

# Include this directory as well
INCLUDES += -I $(MODULE_ARCH_DIR)


